name: first_workflow
env:
  WORKFLOW_VAR: "This is workflow var"

on: 
  workflow_dispatch

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: firstjob-script
        shell: bash
        run: echo Hello World
      - uses: actions/checkout@v4
        name: this is checkout action
      - name: Print to Log
        id: print-to-log
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Paul'
      - name: time
        run: |
          echo "The time of the greeting was at : {{ steps.print-to-log.outputs.time }}"
        

  secondjob:
    env:
      JOB_VAR: "This is a job Var"
    runs-on: ubuntu-latest
    needs: firstjob
    steps:
      - name: secondjob-script
        shell: bash
        run: |
          echo this is multiple line
          echo this is 2nd line
      - name: env variables
        env:
          STEP_VAR: "This is step var"
      - run: |
          echo $WORKFLOW_VAR
          echo $JOB_VAR
          echo $STEP_VAR
          echo "This is secret: ${{ secrets.SOME_SECRET}}"
